spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://dpg-co5qas4f7o1s73a5nebg-a.singapore-postgres.render.com:5432/test_2vh2
    username: test_2vh2_user
    password: 9aUjoIiJLKiWLIk6i8MkJ24BQ9rgtGby
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.1fe17cfbf43477f4
            client-secret: 0ce8177b94b4d4134becfed3c16c86b920ad0234
server:
  port: 9998